display-name = "weirdpercent"
downloads-dir = "~/Downloads"
signature = "Regards,"

[gmail]
default = true
email = "weirdpercent@gmail.com"

backend = "maildir" # imap, maildir or notmuch
maildir-root-dir = "~/Maildir"
imap-host = "imap.gmail.com"
imap-port = 993
imap-login = "weirdpercent@gmail.com"
imap-passwd-cmd = "pass show gmail"

sender = "smtp" # smtp or sendmail
smtp-host = "smtp.gmail.com"
smtp-port = 465
smtp-login = "weirdpercent@gmail.com"
smtp-passwd-cmd = "security find-internet-password -gs gmail -w"
