[helpers]

[default]
depends = ["sway"]

[default.files]
LICENSE = ""
"README.md" = ""
alacritty = "~/.config/alacritty/alacritty.yml"
fish = "~/.config/fish/config.fish"
kitty = "~/.config/kitty/kitty.conf"
mako = "~/.config/mako/config"
rofi = "~/.config/rofi/config.rasi"
starship = "~/.config/starship.toml"
topgrade = "~/.config/topgrade.toml"
zellij = "~/.config/zellij/config.yaml"

[default.variables]

[sway]
depends = ["waybar"]

[sway.files]
sway = "~/.config/sway/config"

[waybar.files]
waybar = "~/.config/waybar/config"
style = "~/.config/waybar/style.css"
